<a href="https://colab.research.google.com/github/hanbitgoun/GJ_AI/blob/main/0630_d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 데이터 불러오기

In [ ]:
import csv
import numpy as np

In [ ]:
with open('/content/abalone_mini.csv') as csvfile:
  csvreader = csv.reader(csvfile)
  rows = []
  for row in csvreader:
    rows.append(row)

In [ ]:
print(rows)

[['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


#### one-hot vector

In [ ]:
data = np.zeros([5,11]) # 5행 11열

# enumerate() : index, element로 이루어진 튜플 생성
# ex) enumerate(rows , start = 100) : 시작 인덱스 100
for n, row in enumerate(rows): 
  print(n, row)
  if row[0] == 'M': data[n,0] = 1
  if row[0] == 'F': data[n,1] = 1
  if row[0] == 'I': data[n,2] = 1

  data[n, 3:] = row[1:]

0 ['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15']
1 ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7']
2 ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9']
3 ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10']
4 ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']


In [ ]:
data

array([[ 1.    ,  0.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 1.    ,  0.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  1.    ,  0.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 1.    ,  0.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 0.    ,  0.    ,  1.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

#### main_exec()

가중치 / 편향

weigtht / bias

parameter

y_hat = (weight * x) + bias

p1(perceptron) x, w 행렬곱 한 결과

In [ ]:
# 독립변수의 개수
input_cnt = 10
# 종속변수의 개수
output_cnt = 1
# 평균, 표준편차
RND_MEAN = 0
RND_STD = 1

# weight, bias를 구하는 함수 model_init() 생성
def model_init():
  global weight, bias
  weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
  bias = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])
  

In [ ]:
weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
print(weight)
print("=======================")
bias = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])
print(bias)

[[-0.05463584]
 [-1.53617316]
 [-0.90573603]
 [ 0.4668781 ]
 [ 0.33802909]
 [ 0.50824631]
 [-2.65531159]
 [-1.34824225]
 [-2.51848279]
 [-0.11771074]]
[-0.68796658]


In [ ]:
print(weight, bias)

[[-0.05463584]
 [-1.53617316]
 [-0.90573603]
 [ 0.4668781 ]
 [ 0.33802909]
 [ 0.50824631]
 [-2.65531159]
 [-1.34824225]
 [-2.51848279]
 [-0.11771074]] [-0.68796658]


In [ ]:
# forward_nueralnet : y_hat
def forward_nueralnet(x):
  y_hat = np.matmul(x, weight) + bias #행렬곱 수행
  return y_hat

In [ ]:
print(data[:, :-1])

In [ ]:
forward_nueralnet(data[:, :-1]) #bias 제외

array([[-2.29804278],
       [-1.30718425],
       [-4.29066353],
       [-2.31630384],
       [-2.08373643]])

In [ ]:
# foward_postproc : mse
def forward_postproc(output, y):
  print("output : \n",output)
  print("y : \n",y)

  diff = output - y #편차
  print("diff : \n",diff)

  square = np.square(diff) #제곱
  print("square : \n",square)

  mse = np.mean(square)
  print("mse : \n",mse)
  return mse

In [ ]:
def run_train(x, y):
  output = forward_nueralnet(x)
  loss = forward_postproc(output, y) #손실함수
  return output, loss

In [ ]:
print(data[:,-1:])

[[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]


In [ ]:
run_train(data[:,:-1,], data[:,-1:])

output : 
 [[-2.29804278]
 [-1.30718425]
 [-4.29066353]
 [-2.31630384]
 [-2.08373643]]
y : 
 [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff : 
 [[-17.29804278]
 [ -8.30718425]
 [-13.29066353]
 [-12.31630384]
 [ -9.08373643]]
square : 
 [[299.22228419]
 [ 69.0093101 ]
 [176.64173715]
 [151.69134027]
 [ 82.5142676 ]]
mse : 
 155.81578786197494


(array([[-2.29804278],
        [-1.30718425],
        [-4.29066353],
        [-2.31630384],
        [-2.08373643]]), 155.81578786197494)

In [ ]:
def main_exec(x, y):
  #import_data()
  model_init()
  run_train(x, y)

In [ ]:
main_exec(data[:,:-1,], data[:,-1:])

output : 
 [[ 0.28343781]
 [-0.035665  ]
 [ 0.60209008]
 [ 0.24592999]
 [ 1.04776503]]
y : 
 [[15.]
 [ 7.]
 [ 9.]
 [10.]
 [ 7.]]
diff : 
 [[-14.71656219]
 [ -7.035665  ]
 [ -8.39790992]
 [ -9.75407001]
 [ -5.95223497]]
square : 
 [[216.57720268]
 [ 49.50058197]
 [ 70.52489098]
 [ 95.14188183]
 [ 35.42910109]]
mse : 
 93.4347317108722


#### 클래스 외부에 함수생성 > 함수중복최소화

In [ ]:
class One_class():
  def __init__(self, x):
    self.x = x

In [ ]:
def main_exec():
  pass


# main_exec > One_class 내부
One_class.c_main_exec = main_exec 
One_class.main_exec_2 = main_exec 

In [ ]:
one_c_value = One_class(1)

In [ ]:
one_c_value.c_main_exec()
one_c_value.main_exec_2()