<a href="https://colab.research.google.com/github/hanbitgoun/GJ_AI/blob/main/deep_learning/0709_d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#### 데이터 불러오기

In [ ]:
df = pd.read_csv('/content/faults.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Y_Minimum              1941 non-null   int64  
 3   Y_Maximum              1941 non-null   int64  
 4   Pixels_Areas           1941 non-null   int64  
 5   X_Perimeter            1941 non-null   int64  
 6   Y_Perimeter            1941 non-null   int64  
 7   Sum_of_Luminosity      1941 non-null   int64  
 8   Minimum_of_Luminosity  1941 non-null   int64  
 9   Maximum_of_Luminosity  1941 non-null   int64  
 10  Length_of_Conveyer     1941 non-null   int64  
 11  TypeOfSteel_A300       1941 non-null   int64  
 12  TypeOfSteel_A400       1941 non-null   int64  
 13  Steel_Plate_Thickness  1941 non-null   int64  
 14  Edges_Index            1941 non-null   float64
 15  Empt

In [ ]:
df_dataset = df[['X_Minimum','X_Maximum','Steel_Plate_Thickness','LogOfAreas',
                 'Pastry','Z_Scratch','Bumps']]
print("df_dataset.shape : ", df_dataset.shape)
print(df_dataset.info())

df_dataset.shape :  (1941, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Steel_Plate_Thickness  1941 non-null   int64  
 3   LogOfAreas             1941 non-null   float64
 4   Pastry                 1941 non-null   int64  
 5   Z_Scratch              1941 non-null   int64  
 6   Bumps                  1941 non-null   int64  
dtypes: float64(1), int64(6)
memory usage: 106.3 KB
None


In [ ]:
df_dataset = np.asarray(df_dataset, dtype='float32')

In [ ]:
df_dataset_x = df_dataset[0:1,:-3] # 독립변수
df_dataset_y = df_dataset[0:1,-3:] # 종속변수

print("df_dataset_x : ",df_dataset_x)
print('df_dataset_x.shape : ',df_dataset_x.shape)
print("df_dataset_y : ",df_dataset_y)
print('df_dataset_y.shape : ',df_dataset_y.shape)

df_dataset_x :  [[42.     50.     80.      2.4265]]
df_dataset_x.shape :  (1, 4)
df_dataset_y :  [[1. 0. 0.]]
df_dataset_y.shape :  (1, 3)


In [ ]:
RND_MEAN = 0
RND_STD = 1

input_cnt = df_dataset_x.shape[-1]  # 독립변수의 개수
output_cnt = df_dataset_y.shape[-1] # 종속변수의 개수

weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
bias = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])

print('weight.shape : ', weight.shape)
print('bias.shape : ', bias.shape)

weight.shape :  (4, 3)
bias.shape :  (3,)


In [ ]:
print("df_dataset_x : \n", df_dataset_x)

print("weight : \n", weight)
print("bias : \n", bias)

df_dataset_x : 
 [[42.     50.     80.      2.4265]]
weight : 
 [[-0.7444182   0.35001641  0.46986175]
 [ 0.43455514  0.23424979  1.49568794]
 [-0.8134322   0.53625438  1.43700191]
 [ 0.5686819  -0.04577269 -1.28662673]]
bias : 
 [-1.46196896  0.20723172 -1.23141231]


In [ ]:
P_1 = np.matmul(df_dataset_x[0], weight[:,0]) + bias[0 ] # perceptron 1
P_2 = np.matmul(df_dataset_x[0], weight[:,1]) + bias[1]
P_3 = np.matmul(df_dataset_x[0], weight[:,2]) + bias[2]

P_total = np.matmul(df_dataset_x, weight) + bias

print(P_1)
print(P_2)
print(P_3)
print()

print(P_total)

-74.69444531417737
69.40969317574974
205.1253316178329

[[-74.69444531  69.40969318 205.12533162]]


#### (Model) Parameter - Weight / Bias

#### HyperParameter - lr / epoch / std / mean

In [ ]:
df = pd.read_csv('/content/faults_mini.csv')
df.info()
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   X_Minimum              10 non-null     int64
 1   Y_Minimum              10 non-null     int64
 2   Pixels_Areas           10 non-null     int64
 3   Steel_Plate_Thickness  10 non-null     int64
 4   Pastry                 10 non-null     int64
 5   Z_Scratch              10 non-null     int64
 6   K_Scatch               10 non-null     int64
dtypes: int64(7)
memory usage: 688.0 bytes


X_Minimum  Y_Minimum  Pixels_Areas  ...  Pastry  Z_Scratch  K_Scatch
0         42     270900           267  ...       1          0         0
1       1084     185575           108  ...       0          0         1
2       1109    1170194           130  ...       0          1         0
3        190     210936           132  ...       1          0         0
4        330     429227           264  ...       1          0         0
5         74     779144          1506  ...       1          0         0
6         51     585861           139  ...       0          1         0
7        397     604478           444  ...       0          1         0
8         43     366881          4048  ...       0          0         1
9         48     377537          3985  ...       0          0         1

[10 rows x 7 columns]

In [ ]:
input_cnt = 4
output_cnt = 3
data = np.asarray(df, dtype='float32')
print(data)

[[4.200000e+01 2.709000e+05 2.670000e+02 8.000000e+01 1.000000e+00
  0.000000e+00 0.000000e+00]
 [1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02 0.000000e+00
  1.000000e+00 0.000000e+00]
 [1.900000e+02 2.109360e+05 1.320000e+02 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [3.300000e+02 4.292270e+05 2.640000e+02 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [7.400000e+01 7.791440e+05 1.506000e+03 1.500000e+02 1.000000e+00
  0.000000e+00 0.000000e+00]
 [5.100000e+01 5.858610e+05 1.390000e+02 7.000000e+01 0.000000e+00
  1.000000e+00 0.000000e+00]
 [3.970000e+02 6.044780e+05 4.440000e+02 7.000000e+01 0.000000e+00
  1.000000e+00 0.000000e+00]
 [4.300000e+01 3.668810e+05 4.048000e+03 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [4.800000e+01 3.775370e+05 3.985000e+03 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]]


In [ ]:
weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])
bias = np.random.normal(RND_MEAN, RND_STD, size = [output_cnt])

print("weight.shape : ", weight.shape)
print("bias.shape : ", bias.shape)
print("data.shape : ", data.shape)

weight.shape :  (4, 3)
bias.shape :  (3,)
data.shape :  (10, 7)


In [ ]:
mb_size     = 2   # mini-batch 크기
train_ratio = 0.8 

MiniBatch_step_count = int(data.shape[0] * train_ratio) // mb_size
print("MiniBatch_step_count :", MiniBatch_step_count)

test_begin_index = MiniBatch_step_count * mb_size
print("test_begin_index : ",test_begin_index)

MiniBatch_step_count : 4
test_begin_index :  8


In [ ]:
shuffle_map = np.arange(data.shape[0])
print(shuffle_map)
print()
np.random.shuffle(shuffle_map)
print(shuffle_map)

[0 1 2 3 4 5 6 7 8 9]

[8 0 9 2 4 6 5 7 3 1]


In [ ]:
mb_data_1 = data[shuffle_map[0:2]]
mb_data_2 = data[shuffle_map[2:4]]
mb_data_3 = data[shuffle_map[4:6]]
mb_data_4 = data[shuffle_map[6:8]]

print(mb_data_1) 
print(mb_data_2) 
print(mb_data_3) 
print(mb_data_4) 

[[1.08400e+03 1.85575e+05 1.08000e+02 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[4.200000e+01 2.709000e+05 2.670000e+02 8.000000e+01 1.000000e+00
  0.000000e+00 0.000000e+00]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02 0.000000e+00
  1.000000e+00 0.000000e+00]]
[[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]
 [4.80000e+01 3.77537e+05 3.98500e+03 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]]
[[4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]
 [7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]


In [ ]:
print("====== 첫 번째 미니배치의 독립변수와 종속변수 ======")
mb_1_train_x = mb_data_1[:, :-3]
mb_1_train_y = mb_data_1[:, -3:]
print("mb_1_train_x : \n", mb_1_train_x)
print("mb_1_train_y : \n", mb_1_train_y)

print("\n====== 두 번째 미니배치의 독립변수와 종속변수 ======")
mb_2_train_x = mb_data_2[:, :-3]
mb_2_train_y = mb_data_2[:, -3:]
print("mb_2_train_x : \n", mb_2_train_x)
print("mb_2_train_y : \n", mb_2_train_y)

print("\n====== 세 번째 미니배치의 독립변수와 종속변수 ======")
mb_3_train_x = mb_data_3[:, :-3]
mb_3_train_y = mb_data_3[:, -3:]
print("mb_3_train_x : \n", mb_3_train_x)
print("mb_3_train_y : \n", mb_3_train_y)

print("\n====== 네 번째 미니배치의 독립변수와 종속변수 ======")
mb_4_train_x = mb_data_4[:, :-3]
mb_4_train_y = mb_data_4[:, -3:]
print("mb_4_train_x : \n", mb_4_train_x)
print("mb_4_train_y : \n", mb_4_train_y)

====== 첫 번째 미니배치의 독립변수와 종속변수 ======
mb_1_train_x : 
 [[1.08400e+03 1.85575e+05 1.08000e+02 4.00000e+01]
 [3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02]]
mb_1_train_y : 
 [[0. 0. 1.]
 [1. 0. 0.]]

====== 두 번째 미니배치의 독립변수와 종속변수 ======
mb_2_train_x : 
 [[4.200000e+01 2.709000e+05 2.670000e+02 8.000000e+01]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02]]
mb_2_train_y : 
 [[1. 0. 0.]
 [0. 1. 0.]]

====== 세 번째 미니배치의 독립변수와 종속변수 ======
mb_3_train_x : 
 [[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01]
 [4.80000e+01 3.77537e+05 3.98500e+03 4.00000e+01]]
mb_3_train_y : 
 [[0. 1. 0.]
 [0. 0. 1.]]

====== 네 번째 미니배치의 독립변수와 종속변수 ======
mb_4_train_x : 
 [[4.30000e+01 3.66881e+05 4.04800e+03 4.00000e+01]
 [7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02]]
mb_4_train_y : 
 [[0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
print("첫 번째 미니배치의 순전파 연산 결과")
mb_1_y_hat_1 = np.matmul(mb_1_train_x, weight[:,0]) + bias[0]
mb_1_y_hat_2 = np.matmul(mb_1_train_x, weight[:,1]) + bias[1]
mb_1_y_hat_3 = np.matmul(mb_1_train_x, weight[:,2]) + bias[2]

print(mb_1_y_hat_1)
print(mb_1_y_hat_2)
print(mb_1_y_hat_3)


print("\n두 번째 미니배치의 순전파 연산 결과")
mb_2_y_hat_1 = np.matmul(mb_2_train_x, weight[:,0]) + bias[0]
mb_2_y_hat_2 = np.matmul(mb_2_train_x, weight[:,1]) + bias[1]
mb_2_y_hat_3 = np.matmul(mb_2_train_x, weight[:,2]) + bias[2]

print(mb_2_y_hat_1)
print(mb_2_y_hat_2)
print(mb_2_y_hat_3)


print("\n세 번째 미니배치의 순전파 연산 결과")
mb_3_y_hat_1 = np.matmul(mb_3_train_x, weight[:,0]) + bias[0]
mb_3_y_hat_2 = np.matmul(mb_3_train_x, weight[:,1]) + bias[1]
mb_3_y_hat_3 = np.matmul(mb_3_train_x, weight[:,2]) + bias[2]

print(mb_3_y_hat_1)
print(mb_3_y_hat_2)
print(mb_3_y_hat_3)

print("\n네 번째 미니배치의 순전파 연산 결과")
mb_4_y_hat_1 = np.matmul(mb_4_train_x, weight[:,0]) + bias[0]
mb_4_y_hat_2 = np.matmul(mb_4_train_x, weight[:,1]) + bias[1]
mb_4_y_hat_3 = np.matmul(mb_4_train_x, weight[:,2]) + bias[2]

print(mb_4_y_hat_1)
print(mb_4_y_hat_2)
print(mb_4_y_hat_3)

첫 번째 미니배치의 순전파 연산 결과
[ 77939.08240854 180219.76678022]
[222739.39653297 513833.67739078]
[-106051.23404913 -246436.34235448]

두 번째 미니배치의 순전파 연산 결과
[113828.43858878 490356.57559634]
[ 324170.84005123 1401176.72110516]
[-155745.83396716 -671553.62772226]

세 번째 미니배치의 순전파 연산 결과
[245527.33104968 162711.73060027]
[701174.86037438 450820.919638  ]
[-336596.08995298 -220579.08922849]

네 번째 미니배치의 순전파 연산 결과
[158322.96241589 328130.21558721]
[438047.38872935 932145.9638387 ]
[-214518.90834904 -448794.87311767]


In [ ]:
mb_total = np.vstack( (mb_data_1, mb_data_2, mb_data_3, mb_data_4) )
mb_total.shape

(8, 7)

In [ ]:
mb_total_x = mb_total[:, :-3] # 독립변수
mb_total_x.shape

(8, 4)

In [ ]:
# 간단한 방법
mb_total_y_hat = np.matmul(mb_total_x, weight) + bias
print(mb_total_y_hat)

[[  -13502.25853453  -141012.69786734  -235380.22432272]
 [  -29629.0359914   -322454.67070004  -546205.58341192]
 [  -18568.17246307  -203087.10452258  -345030.3363477 ]
 [  -81251.52811819  -880576.57553093 -1488216.06826291]
 [  -40314.73217437  -439918.75916136  -745622.6087278 ]
 [  -25044.03207793  -277320.29521752  -486396.85293893]
 [  -24290.88905176  -269206.69992444  -472936.95116515]
 [  -53253.17793371  -582915.69533802  -993571.780734  ]]


In [ ]:
# mb_total_y_hat 값과 동일
print(mb_1_y_hat_1,mb_1_y_hat_2,mb_1_y_hat_3)
print(mb_2_y_hat_1,mb_2_y_hat_2,mb_2_y_hat_3)
print(mb_3_y_hat_1,mb_3_y_hat_2,mb_3_y_hat_3)
print(mb_4_y_hat_1,mb_4_y_hat_2,mb_4_y_hat_3)

[-13502.25853453 -29629.0359914 ] [-141012.69786734 -322454.67070004] [-235380.22432272 -546205.58341192]
[-18568.17246307 -81251.52811819] [-203087.10452258 -880576.57553093] [ -345030.3363477  -1488216.06826292]
[-40314.73217437 -25044.03207793] [-439918.75916136 -277320.29521752] [-745622.6087278  -486396.85293893]
[-24290.88905176 -53253.17793371] [-269206.69992444 -582915.69533802] [-472936.95116515 -993571.780734  ]
